# fly.toml app configuration file generated for discord-standby-bot on 2023-10-02T17:20:43-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discord-standby-bot"
primary_region = "yyz"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  processes = ["app"]

[metrics]
  port = 2112
  path = "/metrics" # default for most prometheus exporters

